export const cards: { id: string, name: string }[] = [
    { id: "!BOUNTYHUNTER_BASE", name: "!BOUNTYHUNTER_BASE" },
    { id: "!BUILDACARD_BASE", name: "!BUILDACARD_BASE" },
    { id: "!CORRUPTED", name: "!CORRUPTED" },
    { id: "!DEATHCARD_BASE", name: "!DEATHCARD_BASE" },
    { id: "!DEATHCARD_LESHY", name: "!DEATHCARD_LESHY" },
    { id: "!DEATHCARD_PIXEL_BASE", name: "!DEATHCARD_PIXEL_BASE" },
    { id: "!DEATHCARD_VICTORY", name: "!DEATHCARD_VICTORY" },
    { id: "!FRIENDCARD_BASE", name: "!FRIENDCARD_BASE" },
    { id: "!INSPECTOR", name: "!INSPECTOR" },
    { id: "!MELTER", name: "!MELTER" },
    { id: "!MYCOCARD_BASE", name: "!MYCOCARD_BASE" },
    { id: "!MYCO_OLD_DATA", name: "!MYCO_OLD_DATA" },
    { id: "!STATIC!GLITCH", name: "!STATIC!GLITCH" },
    { id: "CXformerElk", name: "3LK" },
    { id: "MineCart", name: "49er" },
    { id: "CXformerAdder", name: "ADD3R" },
    { id: "Adder", name: "Adder" },
    { id: "AlarmBot", name: "Alarm Bot" },
    { id: "Alpha", name: "Alpha" },
    { id: "Amalgam", name: "Amalgam" },
    { id: "Amoeba", name: "Amoeba" },
    { id: "Amoebot", name: "Amoebot" },
    { id: "Tree_Hologram", name: "Ancient Fir" },
    { id: "AnnoyTower", name: "Annoy FM" },
    { id: "AntQueen", name: "Ant Queen" },
    { id: "AquaSquirrel", name: "AquaSquirrel" },
    { id: "Automaton", name: "Automaton" },
    { id: "Angler_Fish_Bad", name: "Bad Fish" },
    { id: "BaitBucket", name: "Bait Bucket" },
    { id: "Banshee", name: "Banshee" },
    { id: "Bat", name: "Bat" },
    { id: "Beaver", name: "Beaver" },
    { id: "Bee", name: "Bee" },
    { id: "Beehive", name: "Beehive" },
    { id: "SquidBell", name: "Bell Tentacle" },
    { id: "Goat", name: "Black Goat" },
    { id: "MoxDualBG", name: "Bleene's Mox" },
    { id: "SentinelOrange", name: "Bleene's Vessel" },
    { id: "Bloodhound", name: "Bloodhound" },
    { id: "BlueMage", name: "Blue Mage" },
    { id: "BlueMage_Fused", name: "Blue Sporemage" },
    { id: "BoltHound", name: "Bolthound" },
    { id: "LatcherBomb", name: "Bomb Latcher" },
    { id: "Bonepile", name: "Bone Heap" },
    { id: "BonelordHorn", name: "Bone Lord's Horn" },
    { id: "Bonehound", name: "Bonehound" },
    { id: "Boulder", name: "Boulder" },
    { id: "BridgeRailing", name: "Bridge Rails" },
    { id: "BrokenBot", name: "Broken Bot" },
    { id: "CoinLeft", name: "Broken Obol (left)" },
    { id: "CoinRight", name: "Broken Obol (right)" },
    { id: "AttackConduit", name: "Buff Conduit" },
    { id: "Bullfrog", name: "Bullfrog" },
    { id: "BurrowingTrap", name: "Burrowing Trap" },
    { id: "BustedPrinter", name: "Busted 3D Printer" },
    { id: "CagedWolf", name: "Caged Wolf" },
    { id: "CaptiveFile", name: "Captive File" },
    { id: "Cat", name: "Cat" },
    { id: "JerseyDevil", name: "Child 13" },
    { id: "DausBell", name: "Chime" },
    { id: "Cockroach", name: "Cockroach" },
    { id: "ConduitTower", name: "Conduit Tower" },
    { id: "Maggots", name: "Corpse Maggots" },
    { id: "Coyote", name: "Coyote" },
    { id: "Cuckoo", name: "Cuckoo" },
    { id: "HydraEgg", name: "Curious Egg" },
    { id: "AboveCurve", name: "Curve Hopper" },
    { id: "DUMMY_5-5", name: "DUMMY_5-5" },
    { id: "Dam", name: "Dam" },
    { id: "DeadHand", name: "Dead Hand" },
    { id: "DeadTree", name: "Dead Tree" },
    { id: "DireWolf", name: "Dire Wolf" },
    { id: "DireWolfCub", name: "Dire Wolf Cub" },
    { id: "CloserBot", name: "Double Gunner" },
    { id: "Draugr", name: "Draugr" },
    { id: "DrownedSoul", name: "Drowned Soul" },
    { id: "Elk", name: "Elk" },
    { id: "ElkCub", name: "Elk Fawn" },
    { id: "MoxEmerald", name: "Emerald Mox" },
    { id: "EmptyVessel_GreenGem", name: "Emerald Vessel" },
    { id: "EmptyVessel", name: "Empty Vessel" },
    { id: "BatteryBot", name: "Energy Bot" },
    { id: "EnergyConduit", name: "Energy Conduit" },
    { id: "RoboSkeleton", name: "ExeSkeleton" },
    { id: "Bombbot", name: "Explode Bot" },
    { id: "FactoryConduit", name: "Factory Conduit" },
    { id: "FieldMouse", name: "Field Mice" },
    { id: "Angler_Talking", name: "Fishbot" },
    { id: "AntFlying", name: "Flying Ant" },
    { id: "ForceMage", name: "Force Mage" },
    { id: "FrankNStein", name: "Frank & Stein" },
    { id: "FrozenOpossum", name: "Frozen Opossum" },
    { id: "Tail_Furry", name: "Furry Tail" },
    { id: "XformerGrizzlyBot", name: "GR1ZZ" },
    { id: "XformerGrizzlyBeast", name: "GR1ZZ (transformed)" },
    { id: "EnergyRoller", name: "Gamblobot" },
    { id: "Geck", name: "Geck" },
    { id: "GemExploder", name: "Gem Detonator" },
    { id: "GemFiend", name: "Gem Fiend" },
    { id: "GemShielder", name: "Gem Guardian" },
    { id: "GemRipper", name: "Gembound Ripper" },
    { id: "GemsConduit", name: "Gems Conduit" },
    { id: "GhostShip", name: "Ghost Ship" },
    { id: "GiftBot", name: "Gift Bot" },
    { id: "GoldNugget", name: "Gold Nugget" },
    { id: "PeltGolden", name: "Golden Pelt" },
    { id: "Angler_Fish_Good", name: "Good Fish" },
    { id: "MoxDualGO", name: "Goranj's Mox" },
    { id: "SentinelBlue", name: "Goranj's Vessel" },
    { id: "MarrowMage", name: "Gourmage" },
    { id: "Tree", name: "Grand Fir" },
    { id: "Gravedigger", name: "Gravedigger" },
    { id: "Kraken", name: "Great Kraken" },
    { id: "Shark", name: "Great White" },
    { id: "Smoke_Improved", name: "Greater Smoke" },
    { id: "GreenMage", name: "Green Mage" },
    { id: "Grizzly", name: "Grizzly" },
    { id: "SquidCards", name: "Hand Tentacle" },
    { id: "Hawk", name: "Hawk" },
    { id: "HeadlessHorseman", name: "Headless Horseman" },
    { id: "HealerConduit", name: "Heal Conduit" },
    { id: "Hodag", name: "Hodag" },
    { id: "FlyingMage", name: "Hover Mage" },
    { id: "Hrokkall", name: "Hrokkall" },
    { id: "Hydra", name: "Hydra" },
    { id: "Ijiraq", name: "Ijiraq" },
    { id: "Insectodrone", name: "Insectodrone" },
    { id: "JuniorSage", name: "Junior Sage" },
    { id: "CellGift", name: "Kind Cell" },
    { id: "Kingfisher", name: "Kingfisher" },
    { id: "LeapBot", name: "L33pB0t" },
    { id: "Lammergeier", name: "Lammergeier" },
    { id: "Trap", name: "Leaping Trap" },
    { id: "Librarian", name: "Librarian" },
    { id: "BlueMage_Talking", name: "Lonely Wizbot" },
    { id: "Snelk", name: "Long Elk" },
    { id: "MeatBot", name: "M3atB0t" },
    { id: "MageKnight", name: "Mage Knight" },
    { id: "Pupil", name: "Mage Pupil" },
    { id: "MoxTriple", name: "Magnus Mox" },
    { id: "Magpie", name: "Magpie" },
    { id: "Mantis", name: "Mantis" },
    { id: "MantisGod", name: "Mantis God" },
    { id: "MasterBleene", name: "Master Bleene" },
    { id: "MasterGoranj", name: "Master Goranj" },
    { id: "MasterOrlu", name: "Master Orlu" },
    { id: "MealWorm", name: "Meal Worm" },
    { id: "SquidMirror", name: "Mirror Tentacle" },
    { id: "Mole", name: "Mole" },
    { id: "Mole_Telegrapher", name: "Mole (Telegrapher)" },
    { id: "MoleMan", name: "Mole Man" },
    { id: "Moose", name: "Moose Buck" },
    { id: "Angler_Fish_More", name: "More Fish" },
    { id: "Mothman_Stage3", name: "Mothman" },
    { id: "TechMoxTriple", name: "Mox Module" },
    { id: "BombMaiden", name: "Mrs. Bomb" },
    { id: "MudTurtle", name: "Mud Turtle" },
    { id: "Mummy", name: "Mummy Lord" },
    { id: "Mummy_Telegrapher", name: "Mummy Lord (Telegrapher)" },
    { id: "MuscleMage", name: "Muscle Mage" },
    { id: "Necromancer", name: "Necromancer" },
    { id: "NullConduit", name: "Null Conduit" },
    { id: "Opossum", name: "Opossum" },
    { id: "OrangeMage", name: "Orange Mage" },
    { id: "MoxDualOB", name: "Orlu's Mox" },
    { id: "SentinelGreen", name: "Orlu's Vessel" },
    { id: "Ouroboros", name: "Ouroboros" },
    { id: "Ouroboros_Part3", name: "Ourobot" },
    { id: "Mule", name: "Pack Mule" },
    { id: "PackRat", name: "Pack Rat" },
    { id: "Lice", name: "Pelt Lice" },
    { id: "DeadPets", name: "Pharaoh's Pets" },
    { id: "PlasmaGunner", name: "Plasma Jimmy" },
    { id: "Porcupine", name: "Porcupine" },
    { id: "PracticeMageSmall", name: "Practice Mage" },
    { id: "PracticeMage", name: "Practice Wizard" },
    { id: "Pronghorn", name: "Pronghorn" },
    { id: "XformerPorcupineBot", name: "QU177" },
    { id: "XformerPorcupineBeast", name: "QU177 (transformed)" },
    { id: "CXformerRaven", name: "RAV3N" },
    { id: "Rabbit", name: "Rabbit" },
    { id: "PeltHare", name: "Rabbit Pelt" },
    { id: "Raccoon", name: "Raccoon" },
    { id: "RatKing", name: "Rat King" },
    { id: "Rattler", name: "Rattler" },
    { id: "Raven", name: "Raven" },
    { id: "RavenEgg", name: "Raven Egg" },
    { id: "RedHart", name: "Red Hart" },
    { id: "Revenant", name: "Revenant" },
    { id: "RingWorm", name: "Ring Worm" },
    { id: "Otter", name: "River Otter" },
    { id: "Snapper", name: "River Snapper" },
    { id: "RubyGolem", name: "Ruby Golem" },
    { id: "MoxRuby", name: "Ruby Mox" },
    { id: "EmptyVessel_OrangeGem", name: "Ruby Vessel" },
    { id: "XformerBatBot", name: "S0N1A" },
    { id: "XformerBatBeast", name: "S0N1A (transformed)" },
    { id: "Salmon", name: "Salmon" },
    { id: "MoxSapphire", name: "Sapphire Mox" },
    { id: "EmptyVessel_BlueGem", name: "Sapphire Vessel" },
    { id: "Sarcophagus", name: "Sarcophagus" },
    { id: "SentryBot", name: "Sentry Drone" },
    { id: "SentryBot_Fused", name: "Sentry Spore" },
    { id: "LatcherShield", name: "Shield Latcher" },
    { id: "Shieldbot", name: "Shieldbot" },
    { id: "Shutterbug", name: "Shutterbug" },
    { id: "LatcherBrittle", name: "Skel-e-latcher" },
    { id: "SkeletonMage", name: "Skelemagus" },
    { id: "Skeleton", name: "Skeleton" },
    { id: "Skink", name: "Skink" },
    { id: "Skunk", name: "Skunk" },
    { id: "Sniper", name: "Sniper Bot" },
    { id: "Tree_SnowCovered", name: "Snowy Fir" },
    { id: "Tree_Hologram_SnowCovered", name: "Snowy Fir (hologram)" },
    { id: "Sparrow", name: "Sparrow" },
    { id: "CellTri", name: "Splinter Cell" },
    { id: "FieldMouse_Fused", name: "Spore Mice" },
    { id: "Gravedigger_Fused", name: "Sporedigger" },
    { id: "Squirrel", name: "Squirrel" },
    { id: "SquirrelBall", name: "Squirrel Ball" },
    { id: "Starvation", name: "Starvation" },
    { id: "Steambot", name: "Steambot" },
    { id: "RoboMice", name: "Steel Mice" },
    { id: "StimMage", name: "Stim Mage" },
    { id: "Stinkbug_Talking", name: "Stinkbug" },
    { id: "Stoat", name: "Stoat" },
    { id: "Stoat_Talking", name: "Stoat (talking)" },
    { id: "TrapFrog", name: "Strange Frog" },
    { id: "Mothman_Stage1", name: "Strange Larva" },
    { id: "Mothman_Stage2", name: "Strange Pupa" },
    { id: "Stump", name: "Stump" },
    { id: "Wolf_Talking", name: "Stunted Wolf" },
    { id: "SwapBot", name: "Swapbot" },
    { id: "Tadpole", name: "Tadpole" },
    { id: "DefaultTail", name: "Tail" },
    { id: "Tail_Bird", name: "Tail Feathers" },
    { id: "Daus", name: "The Daus" },
    { id: "!GIANTCARD_MOON", name: "The Moon" },
    { id: "Smoke", name: "The Smoke" },
    { id: "Smoke_NoBones", name: "The Smoke (no bones)" },
    { id: "CardMergeStones", name: "The Stones" },
    { id: "Family", name: "The Walkers" },
    { id: "Thickbot", name: "Thick Droid" },
    { id: "TombRobber", name: "Tomb Robber" },
    { id: "TombStone", name: "Tombstone" },
    { id: "CellBuff", name: "Tough Cell" },
    { id: "Vulture", name: "Turkey Vulture" },
    { id: "CatUndead", name: "Undead Cat" },
    { id: "Urayuli", name: "Urayuli" },
    { id: "CXformerWolf", name: "W07F" },
    { id: "Warren", name: "Warren" },
    { id: "Bull", name: "Wild Bull" },
    { id: "Wolf", name: "Wolf" },
    { id: "WolfCub", name: "Wolf Cub" },
    { id: "PeltWolf", name: "Wolf Pelt" },
    { id: "Wolverine", name: "Wolverine" },
    { id: "Ant", name: "Worker Ant" },
    { id: "Tail_Insect", name: "Wriggling Leg" },
    { id: "SkinkTail", name: "Wriggling Tail" },
    { id: "Zombie", name: "Zombie" }
]

export const abilities: { name: string, description: string }[] = [
    { name: "Rabbit Hole", description: "When a card bearing this sigil is played, a Rabbit is created in your hand. A Rabbit is defined as: 0 Power, 1 Health." },
    { name: "Bees Within", description: "Once a card bearing this sigil is struck, a Bee is created in your hand. A Bee is defined as: 1 Power, 1 Health, Guardian." },
    { name: "Sprinter", description: "At the end of the owner's turn, a card bearing this sigil will move in the direction inscribed in the sigil." },
    { name: "Touch of Death", description: "When a card bearing this sigil damages another creature, that creature perishes." },
    { name: "Fledgling", description: "A card bearing this sigil will grow into a more powerful form after 1 turn on the board." },
    { name: "Dam Builder", description: "When a card bearing this sigil is played, a Dam is created on each empty adjacent space. A Dam is defined as: 0 Power, 2 Health." },
    { name: "Hoarder", description: "When a card bearing this sigil is played, you may search your deck for any card and take it into your hand." },
    { name: "Burrower", description: "When an empty space would be struck, a card bearing this sigil will move to that space to receive the strike instead." },
    { name: "Fecundity", description: "When a card bearing this sigil is played, a copy of it is created in your hand." },
    { name: "Loose Tail", description: "When a card bearing this sigil would be struck, a Tail is created in its place and a card bearing this sigil moves to the right." },
    { name: "Corpse Eater", description: "If a creature that you own perishes by combat, a card bearing this sigil in your hand is automatically played in its place." },
    { name: "Bone King", description: "When a card bearing this sigil dies, 4 bones are awarded instead of 1." },
    { name: "Waterborne", description: "A card bearing this sigil submerges itself during its opponent's turn. While submerged, opposing creatures attack its owner directly." },
    { name: "Unkillable", description: "When a card bearing this sigil perishes, a copy of it is created in your hand." },
    { name: "Sharp Quills", description: "Once a card bearing this sigil is struck, the striker is then dealt a single damage point." },
    { name: "Hefty", description: "At the end of the owner's turn, a card bearing this sigil will move in the direction inscribed in the sigil. Creatures in the way will be pushed in the same direction." },
    { name: "Ant Spawner", description: "When a card bearing this sigil is played, an Ant is created in your hand." },
    { name: "Guardian", description: "When an opposing creature is placed opposite to an empty space, a card bearing this sigil will move to that empty space." },
    { name: "Airborne", description: "A card bearing this sigil will strike an opponent directly, even if there is a creature opposing it." },
    { name: "Many Lives", description: "When a card bearing this sigil is sacrificed it does not perish." },
    { name: "Repulsive", description: "If a creature would attack a card bearing this sigil, it does not." },
    { name: "Worthy Sacrifice", description: "A card bearing this sigil is counted as 3 Blood rather than 1 Blood when sacrificed." },
    { name: "Mighty Leap", description: "A card bearing this sigil will block an opposing creature bearing the Airborne sigil." },
    { name: "Bifurcated Strike", description: "A card bearing this sigil will strike each opposing space to the left and right of the space across from it." },
    { name: "Trifurcated Strike", description: "A card bearing this sigil will strike each opposing space to the left, right, and center of it." },
    { name: "Frozen Away", description: "When a card bearing this sigil perishes, the creature inside is released in its place." },
    { name: "Sinkhole", description: "(no description)" },
    { name: "Bone Digger", description: "At the end of the owner's turn, a card bearing this sigil will generate 1 Bone." },
    { name: "Trinket Bearer", description: "When a card bearing this sigil is played, you will receive a random item as long as you have less than 3 items." },
    { name: "Steel Trap", description: "When a card bearing this sigil perishes, the creature opposing it perishes as well. A pelt is created in your hand." },
    { name: "Amorphous", description: "When a card bearing this sigil is drawn, this sigil is replaced with another sigil at random." },
    { name: "Tidal Lock", description: "At the beginning of its owner's turn, a card bearing this sigil will pull small creatures, like Squirrels, into its orbit." },
    { name: "Moon Strike", description: "A card bearing this sigil will strike each opposing space that is occupied by a creature. It will strike directly if no creatures oppose it." },
    { name: "Leader", description: "Creatures adjacent to a card bearing this sigil gain 1 power." },
    { name: "Brittle", description: "After attacking, a card bearing this sigil perishes." },
    { name: "Skeleton Crew", description: "At the end of the owner's turn, a card bearing this sigil will move in the direction inscribed in the sigil and drop a Skeleton in its old space." },
    { name: "Green Mox", description: "While a card bearing this sigil is on the board, it provides a Green Gem to its owner." },
    { name: "Orange Mox", description: "While a card bearing this sigil is on the board, it provides an Orange Gem to its owner." },
    { name: "Blue Mox", description: "While a card bearing this sigil is on the board, it provides a Blue Gem to its owner." },
    { name: "Gem Animator", description: "Mox cards on the owner's side of the board gain 1 power." },
    { name: "Ruby Heart", description: "When a card bearing this sigil perishes, a Ruby Mox is created in its place." },
    { name: "Mental Gemnastics", description: "When a card bearing this sigil is played, you draw cards equal to the amount of Mox cards on your side of the board." },
    { name: "Gem Dependant", description: "If a card bearing this sigil's owner controls no Mox cards, a card bearing this sigil perishes." },
    { name: "Great Mox", description: "While a card bearing this sigil is on the board, it provides a Green, Orange, and Blue gem to its owner." },
    { name: "Handy", description: "When a card bearing this sigil is played, discard your hand then draw a new hand of 4 cards." },
    { name: "Squirrel Shedder", description: "At the end of the owner's turn, a card bearing this sigil will move in the direction inscribed in the sigil and drop a Squirrel in their old space." },
    { name: "Attack Conduit", description: "Other creatures within a circuit completed by a card bearing this sigil gain 1 power." },
    { name: "Spawn Conduit", description: "Empty spaces within a circuit completed by a card bearing this sigil spawn L33pB0ts at the end of the owner's turn." },
    { name: "Healing Conduit", description: "Other creatures within a circuit completed by a card bearing this sigil are healed at the end of the owner's turn." },
    { name: "Null Conduit", description: "A card bearing this sigil may complete a circuit, but provides no effect." },
    { name: "Battery Bearer", description: "When a card bearing this sigil is played, it provides an Energy Cell to its owner." },
    { name: "Detonator", description: "When a card bearing this sigil dies, the creature opposing it, as well as adjacent friendly creatures, are dealt 10 damage." },
    { name: "Sniper", description: "You may choose which opposing space a card bearing this sigil strikes." },
    { name: "Nano Armor", description: "The first time a card bearing this sigil would take damage, prevent that damage." },
    { name: "Overclocked", description: "A card bearing this sigil has increased power. But, if a card bearing this sigil perishes, it is permanently removed from your deck." },
    { name: "Bomb Latch", description: "When a card bearing this sigil perishes, its owner chooses a creature to gain the Detonator sigil." },
    { name: "Brittle Latch", description: "When a card bearing this sigil perishes, its owner chooses a creature to gain the Brittle sigil." },
    { name: "Shield Latch", description: "When a card bearing this sigil perishes, its owner chooses a creature to gain the Nano Armor sigil." },
    { name: "Dead Byte", description: "When a card bearing this sigil perishes, select a file. Place damage on the scales according to the file's size." },
    { name: "Hostage File", description: "When a card bearing this sigil perishes the file used to create it is really deleted from your Hard Drive." },
    { name: "Transformer", description: "At the beginning of your turn a card bearing this sigil will transform to, or from, Beast mode." },
    { name: "Sentry", description: "When a creature moves into the space opposing a card bearing this sigil, they are dealt 1 damage." },
    { name: "Gem Detonator", description: "When Gem Vessels on the owner's side of the board die, they Detonate (the creature opposing them, as well as adjacent friendly creatures, are dealt 10 damage)." },
    { name: "Gem Guardian", description: "When a card bearing this sigil is played, all Gem Vessels on the owners' side of the board gain Nano Armor." },
    { name: "Vessel Printer", description: "Once a card bearing this sigil is struck, draw a card from your Empty Vessel pile." },
    { name: "Energy Conduit", description: "If a card bearing this sigil is part of a completed circuit, your Energy never depletes." },
    { name: "Bomb Spewer", description: "When a card bearing this sigil is played, fill all empty spaces with Explode Bots." },
    { name: "Handy", description: "When another creature you own dies, it is returned to life and dies again immediately." },
    { name: "Power Dice", description: "Pay 1 Energy to set the power of a card bearing this sigil randomly between 1 and 6." },
    { name: "Activated Random Power Bone", description: "(no description)" },
    { name: "Enlarge", description: "Pay 2 Bones to increase the power and health of a card bearing this sigil by 1." },
    { name: "Swapper", description: "After a card bearing this sigil is dealt damage, swap its Power and Health." },
    { name: "Disentomb", description: "Pay 1 Bone to create a Skeleton in your hand." },
    { name: "Energy Gun", description: "Pay 1 Energy to deal 1 damage to the creature across from a card bearing this sigil." },
    { name: "Bellist", description: "When a card bearing this sigil is played, a Chime is created on each empty adjacent space. A Chime is defined as: 0 Power, 1 Health." },
    { name: "Annoying", description: "The creature opposing a card bearing this sigil gains 1 power." },
    { name: "Gem Spawn Conduit", description: "Empty spaces within a circuit completed by a card bearing this sigil spawn Gem Vessels at the end of the owner's turn." },
    { name: "Gift Bearer", description: "When a card bearing this sigil perishes, a random card is created in your hand." },
    { name: "Looter", description: "When a card bearing this sigil deals damage directly, draw a card for each damage dealt." },
    { name: "True Scholar", description: "If you have a Blue gem, sacrifice a card bearing this sigil to draw 3 cards." },
    { name: "Stimulate", description: "Pay 3 Energy to increase the power and health of a card bearing this sigil by 1." },
    { name: "Marrow Sucker", description: "Pay 2 Bones to heal a card bearing this sigil." },
    { name: "Stinky", description: "The creature opposing a card bearing this sigil loses 1 power." },
    { name: "Buff When Powered", description: "If a card bearing this sigil is within a circuit, it gains 2 power." },
    { name: "Gift When Powered", description: "If a card bearing this sigil is within a circuit when it perishes, a random card is created in your hand." },
    { name: "Trifurcated When Powered", description: "If a card bearing this sigil is within a circuit, it will strike each opposing space to the left, right, and center of it." },
    { name: "Bonehorn", description: "Pay 1 Energy to gain 3 Bones." },
    { name: "Clinger", description: "When one of your creatures is placed in a space, a card bearing this sigil will move towards them as far as possible." },
    { name: "Waterborne (tentacle)", description: "A card bearing this sigil submerges itself during its opponent's turn. While submerged, opposing creatures attack its owner directly." },
    { name: "Blood Guzzler", description: "When a creature bearing this sigil deals damage, it gains 1 health for each damage dealt." },
    { name: "Haunter", description: "When a creature bearing this sigil dies, it haunts the space it died in. Creatures played on this space gain its old sigils." },
    { name: "Exploding Corpse", description: "When a creature bearing this sigil dies, all empty spaces on the board are filled with a Guts card." },
    { name: "Apparition", description: "A creature bearing this sigil gains 1 power when you speak 'Bloody Mary' into a connected microphone up to a total of 13 times." },
    { name: "Virtual Realist", description: "If a VR headset is connected, a creature bearing this sigil may be played without paying its cost." },
    { name: "Head of Edaxio", description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio." },
    { name: "Arms of Edaxio", description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio." },
    { name: "Legs of Edaxio", description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio." },
    { name: "Torso of Edaxio", description: "Edaxio is summoned if you control creatures bearing the sigils of Head, Arms, Legs, and Torso of Edaxio." },
    { name: "Brood Parasite", description: "When a card bearing this sigil is played, an egg is created on the opposing space." },
    { name: "Double Strike", description: "A card bearing this sigil will strike the opposing space an extra time when attacking." },
    { name: "Scavenger", description: "While a card bearing this sigil is on the board, opposing creatures also provide bones when perishing." },
    { name: "Rampager", description: "At the end of the owner's turn, a card bearing this sigil will move in the direction inscribed in the sigil. Creatures in the way will be thrown back behind it." },
    { name: "Morsel", description: "When a card bearing this sigil is sacrificed, it adds its stat values to the card it was sacrificed for." },
    { name: "Blood Lust", description: "When a card bearing this sigil attacks an opposing creature and it perishes, this card gains 1 power." },
    { name: "Made of Stone", description: "A card bearing this sigil is immune to the effects of Touch of Death and Stinky." },
    { name: "Finical Hatchling", description: "A card bearing this sigil hatches when drawn if the numbers 1 to 5 are represented in the health of creatures in your deck, and in their power, and if there is a creature of each tribe in your deck." }
]

export const items: { id: string, name: string }[] = [
    { id: "Battery", name: "Extra Battery" },
    { id: "BirdLegFan", name: "Harpie's Birdleg Fan" },
    { id: "BleachPot", name: "Magickal Bleach" },
    { id: "BombRemote", name: "Mrs. Bomb's Remote" },
    { id: "FishHook", name: "Fish Hook" },
    { id: "FrozenOpossumBottle", name: "Frozen Opossum Bottle" },
    { id: "GoatBottle", name: "Black Goat Bottle" },
    { id: "GooBottle", name: "Failure" },
    { id: "Hammer", name: "Hammer" },
    { id: "Hourglass", name: "Hourglass" },
    { id: "MagnifyingGlass", name: "Magpie's Glass" },
    { id: "PiggyBank", name: "Hoggy Bank" },
    { id: "Pliers", name: "Pliers" },
    { id: "PocketWatch", name: "Wiseclock" },
    { id: "Scissors", name: "Scissors" },
    { id: "ShieldGenerator", name: "Nano Shield Generator" },
    { id: "SpecialDagger", name: "Special Dagger" },
    { id: "SquirrelBottle", name: "Squirrel in a Bottle" },
    { id: "TerrainBottle", name: "Boulder in a Bottle" },
    { id: "TrapperKnife", name: "Skinning Knife" }
]

export const tribes: string[] = [
    "Squirrel",
    "Feathered",
    "Canine",
    "Hooved",
    "Reptilian",
    "Insectoid"
]

export const boons: { name: string, description: string }[] = [
    { name: "Boon of the Ambidextrous", description: "You may draw twice at the beginning of your turn." },
    { name: "Boon of the Magpie's Eye", description: "When you draw from your deck, you may choose any card in your deck to draw." },
    { name: "Boon of the Rabid Squirrel", description: "Your Squirrels will have 1 power." },
    { name: "Boon of Goat's Blood", description: "You will start a battle with a Black Goat on the board." },
    { name: "Boon of the Forest", description: "You will start a battle with Grand Firs on all of your spaces." },
    { name: "Boon of the Bone Lord", description: "You will start a battle with 8 bones." }
]

export const eyeStates: string[] = [
    "Default",
    "Eye missing",
    "Magnificus eye inserted",
    "Goat eye inserted"
]

export const starterDecks: string[] = [
    "Vanilla",
    "MooseBlood",
    "Ants",
    "MantisGod",
    "SubmergeBirds",
    "Bones",
    "FreeReptiles",
    "HydraEggs"
]
